services:
  opadviser:
    build:
      .
    volumes:
      - .:/app
    links:
      - db
    stdin_open: true
    tty: true
  db:
    command:
      - --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql:/var/lib/mysql:delegated
