services:
    web:
        build: .
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "mysql:5.7"
        ports:
            - "3306:3306"
        environment:
            POSTGRES_PASSWORD: hunter2