services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep infinity
    shm_size: 4gb
    volumes:
      - /mnt/sdd/jeseok/opadviser:/opadviser
      - /mnt/sdd/jeseok/mysql:/var/lib/mysql
