services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep infinity
    network_mode: service:db
  db:
    command:
      - --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"
    volumes:
      - /var/lib/mysql:/var/lib/mysql:delegated
      - /var/run/mysqld:/var/run/mysqld:delegated
