services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command:
      - sleep infinity
    network_mode: service:db
  db:
    command:
      - --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - /mysql:/var/lib/mysql:delegated
      - /var/run/mysqld:/var/run/mysqld:delegated
  volumes:
    /var/run/mysqld