services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    cgroup: host
    command:
      - sleep infinity
    privileged: true
    shm_size: 4gb
    volumes:
      - /mnt/sdf/jeseok/opadviser:/opadviser
      - /mnt/sdf/jeseok/mysql:/var/lib/mysql
